name: 'PR Deploy'
description: 'Automate PR deployment into isolated Docker containers for Flask apps'
inputs:
  server_host:
    description: 'SSH host of the server'
    required: true
    default: ${{ secrets.HOST }}
  server_username:
    description: 'SSH username'
    required: true
    default: ${{ secrets.USERNAME }}
  server_password:
    description: 'SSH password'
    required: true
    default: ${{ secrets.PASSWORD }}
  server_port:
    description: 'SSH port'
    required: true
    default: ${{ secrets.PORT }}
  dir:
    description: 'Directory in the repository where the Dockerfile or start command is located'
    required: false
    default: '.'
  dockerfile:
    description: 'Path to the Dockerfile'
    required: false
  start_command:
    description: 'Command to start the Flask application if Dockerfile is not provided'
    required: false
    default: 'flask run --host=0.0.0.0'
  exposed_port:
    description: 'Port to expose in the container'
    required: true
  env:
    description: 'Environment variables to pass to the container'
    required: false
runs:
  using: 'bash'
  steps:
    - name: Run deployment script
      run: ./deploy.sh
